# GitHub Sponsors configuration
# https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

github: [SoulofSorrow]
# patreon: username
# ko_fi: username
# custom: ['https://paypal.me/username']
