kind: pipeline
type: docker
name: build-and-push

steps:
  # Build and push Docker image to Gitea registry
  - name: build-and-push-docker
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      GITEA_REGISTRY:
        from_secret: GITEA_REGISTRY
      DOCKER_REPO:
        from_secret: docker_repo
      GITEA_USER:
        from_secret: gitea_username
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - echo "$GITEA_TOKEN" | docker login $GITEA_REGISTRY -u "$GITEA_USER" --password-stdin
      - docker build -t $DOCKER_REPO:latest -t $DOCKER_REPO:${DRONE_COMMIT_SHA:0:8} -t $DOCKER_REPO:${DRONE_TAG} .
      - docker push $DOCKER_REPO:latest
      - docker push $DOCKER_REPO:${DRONE_COMMIT_SHA:0:8}
      - if [ -n "$DRONE_TAG" ]; then docker push $DOCKER_REPO:${DRONE_TAG}; fi
    when:
      event:
        - push
        - tag

  # Optional: Send notification on success
  - name: notify-success
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhook_url
      content_type: application/json
      template: >
        {
          "status": "success",
          "repo": "{{ repo.name }}",
          "commit": "{{ build.commit }}",
          "branch": "{{ build.branch }}",
          "author": "{{ build.author }}",
          "message": "{{ build.message }}"
        }
    when:
      status:
        - success
    failure: ignore

  # Optional: Send notification on failure
  - name: notify-failure
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhook_url
      content_type: application/json
      template: >
        {
          "status": "failure",
          "repo": "{{ repo.name }}",
          "commit": "{{ build.commit }}",
          "branch": "{{ build.branch }}",
          "author": "{{ build.author }}",
          "message": "{{ build.message }}"
        }
    when:
      status:
        - failure
    failure: ignore

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---
# Multi-architecture build (optional)
kind: pipeline
type: docker
name: build-multi-arch

steps:
  - name: build-and-push-multiarch
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      GITEA_REGISTRY:
        from_secret: GITEA_REGISTRY
      DOCKER_REPO:
        from_secret: docker_repo
      GITEA_USER:
        from_secret: gitea_username
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - echo "$GITEA_TOKEN" | docker login $GITEA_REGISTRY -u "$GITEA_USER" --password-stdin
      - docker buildx create --use --name multiarch-builder || true
      - docker buildx build --platform linux/amd64,linux/arm64 --build-arg BUILDKIT_INLINE_CACHE=1 -t $DOCKER_REPO:latest -t $DOCKER_REPO:${DRONE_COMMIT_SHA:0:8} --push .
    when:
      event:
        - tag
      ref:
        - refs/tags/v*

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

depends_on:
  - build-and-push

---
# Trigger pipeline for specific branches
kind: pipeline
type: docker
name: development-build

steps:
  - name: build-dev-image
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      GITEA_REGISTRY:
        from_secret: GITEA_REGISTRY
      DOCKER_REPO:
        from_secret: docker_repo
      GITEA_USER:
        from_secret: gitea_username
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - echo "$GITEA_TOKEN" | docker login $GITEA_REGISTRY -u "$GITEA_USER" --password-stdin
      - docker build -t $DOCKER_REPO:dev-${DRONE_BRANCH} -t $DOCKER_REPO:dev-${DRONE_COMMIT_SHA:0:8} .
      - docker push $DOCKER_REPO:dev-${DRONE_BRANCH}
      - docker push $DOCKER_REPO:dev-${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - develop
        - dev/*
      event:
        - push

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
    - master
    - develop
    - dev/*
  event:
    - push
    - tag
    - pull_request
