---
kind: pipeline
type: docker
name: build-and-push

services:
  - name: docker
    image: docker:27-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - "dockerd"
      - "--host=tcp://0.0.0.0:2375"
      - "--tls=false"
    volumes:
      - name: docker-storage
        path: /var/lib/docker

steps:
  - name: build-and-push-docker
    image: docker:27-cli
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
      GITEA_REGISTRY:
        from_secret: GITEA_REGISTRY
      DOCKER_REPO:
        from_secret: docker_repo
      GITEA_USER:
        from_secret: gitea_username
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - sleep 15
      - until docker info >/dev/null 2>&1; do echo "Waiting for docker daemon..."; sleep 3; done
      - docker info
      - echo "$GITEA_TOKEN" | docker login "$GITEA_REGISTRY" -u "$GITEA_USER" --password-stdin
      - export SHORT_SHA=$(echo $DRONE_COMMIT_SHA | cut -c1-8)
      - docker build -t $DOCKER_REPO:latest -t $DOCKER_REPO:$SHORT_SHA .
      - docker push $DOCKER_REPO:latest
      - docker push $DOCKER_REPO:$SHORT_SHA
    when:
      event:
        - push
        - tag

volumes:
  - name: docker-storage
    temp: {}

---
kind: pipeline
type: docker
name: build-multi-arch

depends_on:
  - build-and-push

services:
  - name: docker
    image: docker:27-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - "dockerd"
      - "--host=tcp://0.0.0.0:2375"
      - "--tls=false"
    volumes:
      - name: docker-storage
        path: /var/lib/docker

steps:
  - name: build-and-push-multiarch
    image: docker:27-cli
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
      DOCKER_CLI_EXPERIMENTAL: enabled
      GITEA_REGISTRY:
        from_secret: GITEA_REGISTRY
      DOCKER_REPO:
        from_secret: docker_repo
      GITEA_USER:
        from_secret: gitea_username
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - sleep 15
      - until docker info >/dev/null 2>&1; do echo "Waiting for docker daemon..."; sleep 3; done
      - docker info
      - echo "$GITEA_TOKEN" | docker login "$GITEA_REGISTRY" -u "$GITEA_USER" --password-stdin
      - docker buildx create --use --name multiarch-builder --driver docker-container || true
      - export SHORT_SHA=$(echo $DRONE_COMMIT_SHA | cut -c1-8)
      - docker buildx build --platform linux/amd64,linux/arm64 --build-arg BUILDKIT_INLINE_CACHE=1 -t $DOCKER_REPO:latest -t $DOCKER_REPO:$SHORT_SHA --push .
    when:
      event:
        - tag
      ref:
        - refs/tags/v*

volumes:
  - name: docker-storage
    temp: {}

---
kind: pipeline
type: docker
name: development-build

services:
  - name: docker
    image: docker:27-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - "dockerd"
      - "--host=tcp://0.0.0.0:2375"
      - "--tls=false"
    volumes:
      - name: docker-storage
        path: /var/lib/docker

steps:
  - name: build-dev-image
    image: docker:27-cli
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
      GITEA_REGISTRY:
        from_secret: GITEA_REGISTRY
      DOCKER_REPO:
        from_secret: docker_repo
      GITEA_USER:
        from_secret: gitea_username
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - sleep 15
      - until docker info >/dev/null 2>&1; do echo "Waiting for docker daemon..."; sleep 3; done
      - docker info
      - echo "$GITEA_TOKEN" | docker login "$GITEA_REGISTRY" -u "$GITEA_USER" --password-stdin
      - export SHORT_SHA=$(echo $DRONE_COMMIT_SHA | cut -c1-8)
      - docker build -t $DOCKER_REPO:dev-$DRONE_BRANCH -t $DOCKER_REPO:dev-$SHORT_SHA .
      - docker push $DOCKER_REPO:dev-$DRONE_BRANCH
      - docker push $DOCKER_REPO:dev-$SHORT_SHA
    when:
      branch:
        - develop
        - dev/*
      event:
        - push

volumes:
  - name: docker-storage
    temp: {}