---
kind: pipeline
type: docker
name: build-and-push

services:
  - name: docker
    image: docker:27-dind
    privileged: true
    command:
      - "--host=tcp://0.0.0.0:2375"
      - "--tls=false"
    volumes:
      - name: docker-storage
        path: /var/lib/docker

steps:
  - name: build-and-push-docker
    image: docker:27-cli
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
    settings:
      registry:
        from_secret: GITEA_REGISTRY
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_token
      repo:
        from_secret: docker_repo
    commands:
      - sleep 5
      - docker info
      - echo "$${password}" | docker login $${registry} -u "$${username}" --password-stdin
      - export SHORT_SHA=$(echo ${DRONE_COMMIT_SHA} | cut -c1-8)
      - docker build -t $${repo}:latest -t $${repo}:${SHORT_SHA} .
      - docker push $${repo}:latest
      - docker push $${repo}:${SHORT_SHA}
    when:
      event:
        - push
        - tag

volumes:
  - name: docker-storage
    temp: {}

---
kind: pipeline
type: docker
name: build-multi-arch

depends_on:
  - build-and-push

services:
  - name: docker
    image: docker:27-dind
    privileged: true
    command:
      - "--host=tcp://0.0.0.0:2375"
      - "--tls=false"
    volumes:
      - name: docker-storage
        path: /var/lib/docker

steps:
  - name: build-and-push-multiarch
    image: docker:27-cli
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
      DOCKER_CLI_EXPERIMENTAL: enabled
    settings:
      registry:
        from_secret: GITEA_REGISTRY
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_token
      repo:
        from_secret: docker_repo
    commands:
      - sleep 5
      - docker info
      - echo "$${password}" | docker login $${registry} -u "$${username}" --password-stdin
      - docker buildx create --use --name multiarch-builder --driver docker-container || true
      - export SHORT_SHA=$(echo ${DRONE_COMMIT_SHA} | cut -c1-8)
      - docker buildx build --platform linux/amd64,linux/arm64 --build-arg BUILDKIT_INLINE_CACHE=1 -t $${repo}:latest -t $${repo}:${SHORT_SHA} --push .
    when:
      event:
        - tag
      ref:
        - refs/tags/v*

volumes:
  - name: docker-storage
    temp: {}

---
kind: pipeline
type: docker
name: development-build

services:
  - name: docker
    image: docker:27-dind
    privileged: true
    command:
      - "--host=tcp://0.0.0.0:2375"
      - "--tls=false"
    volumes:
      - name: docker-storage
        path: /var/lib/docker

steps:
  - name: build-dev-image
    image: docker:27-cli
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
    settings:
      registry:
        from_secret: GITEA_REGISTRY
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_token
      repo:
        from_secret: docker_repo
    commands:
      - sleep 5
      - docker info
      - echo "$${password}" | docker login $${registry} -u "$${username}" --password-stdin
      - export SHORT_SHA=$(echo ${DRONE_COMMIT_SHA} | cut -c1-8)
      - docker build -t $${repo}:dev-${DRONE_BRANCH} -t $${repo}:dev-${SHORT_SHA} .
      - docker push $${repo}:dev-${DRONE_BRANCH}
      - docker push $${repo}:dev-${SHORT_SHA}
    when:
      branch:
        - develop
        - dev/*
      event:
        - push

volumes:
  - name: docker-storage
    temp: {}