kind: pipeline
type: docker
name: build-and-push

steps:
  # Build and push Docker image to Gitea registry
  - name: build-and-push-docker
    image: plugins/docker:24
    settings:
      registry:
        from_secret: GITEA_REGISTRY
      repo:
        from_secret: docker_repo
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_TAG}
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_token
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: Dockerfile
      context: .
    when:
      event:
        - push
        - tag

  # Optional: Send notification on success
  - name: notify-success
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhook_url
      content_type: application/json
      template: |
        {
          "status": "success",
          "repo": "{{ repo.name }}",
          "commit": "{{ build.commit }}",
          "branch": "{{ build.branch }}",
          "author": "{{ build.author }}",
          "message": "{{ build.message }}"
        }
    when:
      status:
        - success
    failure: ignore

  # Optional: Send notification on failure
  - name: notify-failure
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhook_url
      content_type: application/json
      template: |
        {
          "status": "failure",
          "repo": "{{ repo.name }}",
          "commit": "{{ build.commit }}",
          "branch": "{{ build.branch }}",
          "author": "{{ build.author }}",
          "message": "{{ build.message }}"
        }
    when:
      status:
        - failure
    failure: ignore

---
# Multi-architecture build (optional)
kind: pipeline
type: docker
name: build-multi-arch

steps:
  - name: build-and-push-multiarch
    image: plugins/docker:24
    settings:
      registry:
        from_secret: GITEA_REGISTRY
      repo:
        from_secret: docker_repo
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_token
      dockerfile: Dockerfile
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      event:
        - tag
      ref:
        - refs/tags/v*

depends_on:
  - build-and-push

---
# Trigger pipeline for specific branches
kind: pipeline
type: docker
name: development-build

steps:
  - name: build-dev-image
    image: plugins/docker:24
    settings:
      registry:
        from_secret: GITEA_REGISTRY
      repo:
        from_secret: docker_repo
      tags:
        - dev-${DRONE_BRANCH}
        - dev-${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_token
      dockerfile: Dockerfile
      context: .
    when:
      branch:
        - develop
        - dev/*
      event:
        - push

trigger:
  branch:
    - main
    - master
    - develop
    - dev/*
  event:
    - push
    - tag
    - pull_request
